import unittest
from pathlib import Path


class DashboardTests(unittest.TestCase):
    def test_dashboard_has_operator_overview_charts_and_collapsible_sections(self):
        source = Path("dashboard/app.py").read_text()

        self.assertIn("Operator Overview", source)
        self.assertIn("Trading Operations Console", source)
        self.assertIn("quick-nav", source)
        self.assertIn("top-status-bar", source)
        self.assertIn("metric-grid", source)
        self.assertIn("cockpit-grid", source)
        self.assertIn("visual-grid", source)
        self.assertIn("window-grid", source)
        self.assertIn("def _render_top_status_bar", source)
        self.assertIn("def _render_metric_cards", source)
        self.assertIn("def _render_operator_cockpit", source)
        self.assertIn("def _render_arc_gauge", source)
        self.assertIn("def _render_attribution_stack_chart", source)
        self.assertIn("def _render_operator_windows", source)
        self.assertIn("Account Window", source)
        self.assertIn("System Window", source)
        self.assertIn("Actions Window", source)
        self.assertIn("Data Window", source)
        self.assertIn("Alpha Window", source)
        self.assertIn("Decision Window", source)
        self.assertIn("def _render_bar_chart", source)
        self.assertIn("def _render_line_chart", source)
        self.assertIn("def _render_command_center", source)
        self.assertIn("def _priority_rows", source)
        self.assertIn("def _render_priority_queue", source)
        self.assertIn("details.detail-panel", source)
        self.assertIn("Priority Queue", source)
        self.assertIn("Cash", source)
        self.assertIn("Turnover", source)
        self.assertIn("Commands", source)
        self.assertIn("Attribution Stack", source)
        self.assertIn("Freshness Age (hours)", source)
        self.assertIn("Residual Alpha Candidate", source)
        self.assertIn("Recent Command Status", source)

    def test_displayed_dashboard_content_is_not_truncated(self):
        source = Path("dashboard/app.py").read_text()
        governance_start = source.index("def _compact_governance")
        ledger_start = source.index("def _compact_ledger")
        function_source = source[governance_start:ledger_start]

        self.assertIn("_enrich_position_explanations_from_ledger", function_source)
        self.assertIn('"position_explanations": _sort_by_current_weight(explanations)', function_source)
        self.assertIn('"final_explanation"', source)
        self.assertIn('"llm_effect"', source)
        self.assertIn("def _sort_by_current_weight", function_source)
        self.assertNotIn('"position_explanations": (portfolio.get("position_explanations") or [])[:5]', function_source)
        self.assertNotIn("[:4]", source)
        self.assertNotIn("[:5]", source)
        self.assertNotIn("[:6]", source)
        self.assertNotIn("[:160]", source)
        self.assertNotIn("[:180]", source)
        self.assertNotIn("CronRunLog.started_at)).limit", source)

    def test_dashboard_ledger_uses_real_ticker_rows_and_lifecycle_fields(self):
        source = Path("dashboard/app.py").read_text()
        ledger_start = source.index("def _compact_ledger")
        render_start = source.index("def render_dashboard")
        function_source = source[ledger_start:render_start]

        self.assertIn('rows = _ledger_rows_from_tickers(ledger.get("tickers") or {})', function_source)
        self.assertIn('"target_builder_target": lifecycle.get("target_builder_target")', function_source)
        self.assertIn('"diagnostic_llm_target": lifecycle.get("diagnostic_llm_target")', function_source)
        self.assertIn('"validated_advisory_delta": lifecycle.get("validated_advisory_delta")', function_source)
        self.assertIn('"final_target_authority": final_target_label.get("authority")', function_source)
        self.assertIn('"target_builder_target_authority": tb_target_label.get("authority")', function_source)
        self.assertIn('"diagnostic_llm_target_authority": llm_target_label.get("authority")', function_source)
        self.assertIn('"validated_advisory_delta_authority": advisory_delta_label.get("authority")', function_source)
        self.assertIn('"advisory_validator_result": advisory.get("validator_result")', function_source)
        self.assertIn('"ticker_role": policy.get("ticker_role")', function_source)
        self.assertIn('"policy_cap_applied": policy.get("policy_cap_applied")', function_source)
        self.assertIn('"qc_status": raw.get("qc_status")', function_source)
        self.assertIn('"entered_via_hedge_path": hedge_path.get("entered_via_hedge_path")', function_source)

    def test_dashboard_surfaces_weight_source_contract(self):
        source = Path("dashboard/app.py").read_text()

        self.assertIn("weight_source_contract", source)
        self.assertIn("def _weight_source_contract_dashboard", source)
        self.assertIn("def _render_weight_source_contract", source)
        self.assertIn("Weight Source Contract", source)
        self.assertIn("dashboard_weight_source_labels", source)
        self.assertIn("classify_weight_column", source)
        self.assertIn("weight-executable", source)
        self.assertIn("weight-advisory", source)
        self.assertIn("weight-reference", source)
        self.assertIn("final_target_authority", source)
        self.assertIn("diagnostic_llm_target_authority", source)

    def test_dashboard_surfaces_target_path_visibility(self):
        source = Path("dashboard/app.py").read_text()

        self.assertIn("build_target_path_visibility", source)
        self.assertIn('"target_path_visibility": build_target_path_visibility(risk)', source)
        self.assertIn("def _render_target_path_visibility", source)
        self.assertIn("Target Path", source)
        self.assertIn("Executable Truths", source)
        self.assertIn("Diagnostic / Shadow Surfaces", source)
        self.assertIn("Target Path Stages", source)
        self.assertIn("Stage Mutation Attribution", source)
        self.assertIn("Executable vs Diagnostic Weights", source)
        self.assertIn("actual_holdings", source)
        self.assertIn("risk_approved_target", source)
        self.assertIn("envelope_final_target", source)
        self.assertIn("legacy_dict_final_target", source)
        self.assertIn("advisory_llm_weight", source)
        self.assertIn("pc_shadow_reference_weight", source)
        self.assertIn("safety_effect", source)

    def test_dashboard_reads_stage_telemetry_from_agent_step_log(self):
        source = Path("dashboard/app.py").read_text()
        pipeline_source = Path("services/pipeline.py").read_text()

        self.assertIn("AgentStepLog", source)
        self.assertIn("def _latest_stage_metrics", source)
        self.assertIn('"prompt_tokens": (row.token_usage or {}).get("prompt_tokens")', source)
        self.assertIn("Pipeline Stage Telemetry", source)
        self.assertIn('"6c_pc_eval"', pipeline_source)
        self.assertIn('"6cb_final_policy_cap"', pipeline_source)
        self.assertNotIn('"6c_portfolio_construction_evaluation"', pipeline_source)
        self.assertNotIn('"6cb_final_execution_policy_cap"', pipeline_source)

    def test_dashboard_surfaces_portfolio_construction_evaluation(self):
        source = Path("dashboard/app.py").read_text()

        self.assertIn("portfolio_construction_evaluation", source)
        self.assertIn("portfolio_construction_payload", source)
        self.assertIn("portfolio_construction_objective", source)
        self.assertIn("def _compact_portfolio_construction_evaluation", source)
        self.assertIn("def _compact_portfolio_construction_payload", source)
        self.assertIn("def _portfolio_construction_objective_status", source)
        self.assertIn("def _render_portfolio_construction_objective", source)
        self.assertIn("Portfolio Construction Evaluation", source)
        self.assertIn("Portfolio Construction Objective", source)
        self.assertIn("portfolio_construction_readiness", source)
        self.assertIn("Portfolio Construction Readiness", source)
        self.assertIn("portfolio_construction_promotion_gate", source)
        self.assertIn("Portfolio Construction Promotion Gate", source)
        self.assertIn("final_validation", source)
        self.assertIn("Final Risk Validation", source)
        self.assertIn('"primary": objective.get("primary")', source)
        self.assertIn('"subject_to": objective.get("subject_to") or []', source)
        self.assertIn('"effective_n_before": payload.get("effective_n_before")', source)
        self.assertIn('"effective_n_after": payload.get("effective_n_after")', source)
        self.assertIn("Factor Exposure Before / After", source)
        self.assertIn("Basket Exposure Before / After", source)
        self.assertIn("Weight Change Reasons", source)
        self.assertIn("Signal-Weighted Objective Rows", source)
        self.assertIn('"portfolio_construction_target": lifecycle.get("portfolio_construction_target")', source)
        self.assertIn('"signal_weighted_effective_n_before": payload.get("signal_weighted_effective_n_before")', source)
        self.assertIn('"signal_alignment_score_after": payload.get("signal_alignment_score_after")', source)
        self.assertIn('"signal_objective_rows": payload.get("signal_objective_rows") or []', source)
        self.assertIn('"independence_adjusted_net_signal_effective_n_before": payload.get("independence_adjusted_net_signal_effective_n_before")', source)
        self.assertIn('"alpha_decision_objective_rows": payload.get("alpha_decision_objective_rows") or []', source)
        self.assertIn('"strategy_cluster_exposure_rows": payload.get("strategy_cluster_exposure_rows") or []', source)
        self.assertIn("Alpha Decision Objective Rows", source)
        self.assertIn("Strategy Cluster Exposure Rows", source)
        self.assertIn("estimated_ibkr_cost_pct", source)
        self.assertIn("cost_adjusted_edge", source)

    def test_dashboard_surfaces_data_quality_audit_trend(self):
        source = Path("dashboard/app.py").read_text()

        self.assertIn("DATA_QUALITY_AUDIT_NAME", source)
        self.assertIn("def _data_quality_audit_trend", source)
        self.assertIn("to_regclass('public.data_quality_audit')", source)
        self.assertIn("Data Quality Audit Trend", source)
        self.assertIn("def _render_data_quality_audit", source)
        self.assertIn('"unit_risk_count"', source)
        self.assertIn('"high_drift_classes"', source)

    def test_dashboard_surfaces_execution_control_diagnostics(self):
        source = Path("dashboard/app.py").read_text()

        self.assertIn("AccountStateSnapshot", source)
        self.assertIn("CommandLifecycleEvent", source)
        self.assertIn("def _execution_control_status", source)
        self.assertIn('"execution_control": execution_control', source)
        self.assertIn("Execution Control", source)
        self.assertIn("Account State Guard", source)
        self.assertIn("Auto Pause", source)
        self.assertIn("Command Lifecycle Events", source)
        self.assertIn("Recent QC Commands", source)
        self.assertIn("display_status", source)
        self.assertIn("lifecycle_display_status", source)
        self.assertIn("lifecycle_status_source", source)
        self.assertIn("def _lifecycle_status_by_command", source)
        self.assertIn("Active Execution", source)
        self.assertIn("Active Execution Target vs Actual Drift", source)
        self.assertIn("Active Execution Events", source)
        self.assertIn("def _compact_active_execution_panel", source)
        self.assertIn("def _target_actual_drift_rows", source)
        self.assertIn('"execution_contract": "accepted_is_not_reconciled"', source)
        self.assertIn('"can_ordinary_rebalance"', source)
        self.assertIn('"can_reduce_only"', source)
        self.assertIn('"stale": stale.get("is_stale")', source)
        self.assertIn('"stale_reason": stale.get("reason")', source)
        self.assertIn('"stale_auto_action": stale.get("auto_action")', source)
        self.assertIn('"stale_operator_action": stale.get("operator_action")', source)
        self.assertIn("def _active_execution_stale_status", source)
        self.assertIn('"active_command_id": getattr(row, "active_command_id", None)', source)
        self.assertIn('"active_execution_status": getattr(row, "active_execution_status", None)', source)
        self.assertIn('"execution_lifecycle_config": (execution_lifecycle.value if execution_lifecycle else {}) or {}', source)
        self.assertIn('ExecutionLog.qc_status.in_((', source)
        self.assertIn('"timeout_no_ack"', source)
        self.assertIn("DeferredExecutionLedger", source)
        self.assertIn("Deferred Execution Pressure", source)
        self.assertIn("Deferred Execution Ledger", source)
        self.assertIn("def _compact_deferred_execution_row", source)
        self.assertIn("build_reconciliation_lag_report", source)
        self.assertIn("Reconciliation Lag", source)
        self.assertIn("Accepted Commands Without Reconciliation", source)
        self.assertIn('"reconciliation_lag": build_reconciliation_lag_report', source)
        self.assertIn('"account_state_guard": _compact_account_state_guard', source)
        self.assertIn('"auto_pause": _compact_auto_pause', source)
        self.assertIn('"qc_status": row.qc_status', source)
        self.assertIn('"qc_rejection_reason": row.qc_rejection_reason', source)
        self.assertIn('"execution_state": response.get("execution_state")', source)
        self.assertIn('"submitted_order_count": order_summary.get("submitted_order_count")', source)
        self.assertIn('"open_order_count": order_summary.get("open_order_count_after")', source)
        self.assertIn('"event_type": row.event_type', source)
        self.assertIn('"payload_keys": sorted(payload.keys())', source)

    def test_dashboard_surfaces_etf_strategy_evidence(self):
        source = Path("dashboard/app.py").read_text()

        self.assertIn("def _latest_strategy_evidence", source)
        self.assertIn('AgentStepLog.stage == "2d_evidence_scorecard"', source)
        self.assertIn("def _compact_strategy_evidence", source)
        self.assertIn("def _compact_evidence_card", source)
        self.assertIn("def _strategy_evidence_dashboard_status", source)
        self.assertIn("def _render_strategy_evidence", source)
        self.assertIn('"strategy_evidence": strategy_evidence', source)
        self.assertIn("ETF / Strategy Evidence", source)
        self.assertIn("Strategy Diversity", source)
        self.assertIn("Strategy Independence Baseline", source)
        self.assertIn("Low-Correlation Strategy Pairs", source)
        self.assertIn("High-Correlation Strategy Pairs", source)
        self.assertIn("Strategy Correlation Pair Rows", source)
        self.assertIn("Strategy Family Correlation Rows", source)
        self.assertIn("Strategy Family Rows", source)
        self.assertIn("Strategy Diversity Rows", source)
        self.assertIn("Evidence Matrix Default View", source)
        self.assertIn("Evidence Matrix Collapsed Watch/Abstain", source)
        self.assertIn('"evidence_matrix_rows": visible_card_rows', source)
        self.assertIn('"evidence_matrix_collapsed_rows": collapsed_card_rows', source)
        self.assertIn('"default_visible_vote_statuses": ["voted", "mapping_error"]', source)
        self.assertIn("Mapping And Safety Warnings", source)
        self.assertIn("Role / Action Summary", source)
        self.assertIn("Conviction Status Summary", source)
        self.assertIn("Conviction Display Contract", source)
        self.assertIn("Evidence Cap Observe", source)
        self.assertIn("Evidence Cap Observe Rows", source)
        self.assertIn("Evidence Mapping Error Dedupe Rows", source)
        self.assertIn("def _compact_evidence_cap_observe", source)
        self.assertIn("def _compact_strategy_independence", source)
        self.assertIn('"evidence_cap_observe": evidence_cap_observe', source)
        self.assertIn('"strategy_independence": strategy_independence', source)
        self.assertIn('"baseline_established": baseline.get("baseline_established")', source)
        self.assertIn('"vote_status": card.get("vote_status")', source)
        self.assertIn('"vote_dedupe_key": vote_diag.get("dedupe_key")', source)
        self.assertIn('"main_abstain_reason": _main_abstain_reason', source)
        self.assertIn('"conviction_display": _format_conviction_display(conviction)', source)
        self.assertIn('"conviction_status": card.get("conviction_status")', source)
        self.assertIn('"conviction_source_bucket": card.get("conviction_source_bucket")', source)
        self.assertIn('"conviction_n": conviction_n', source)
        self.assertIn('"missing_safety_fields": diagnostics.get("missing_safety_fields") or []', source)
        self.assertIn('"allowed_actions": diagnostics.get("allowed_actions") or []', source)
        self.assertIn('"strategy_diversity": strategy_diversity', source)
        self.assertIn('"diversity_family_rows": strategy_diversity.get("family_rows") or []', source)
        self.assertIn('"canonical_family": row.get("canonical_family")', source)
        self.assertIn('"alpha_source": row.get("alpha_source")', source)
        render_start = source.index("def _render_strategy_evidence")
        render_end = source.index("def _render_live_signal_conviction")
        render_source = source[render_start:render_end]
        self.assertLess(
            render_source.index('independence = evidence.get("strategy_independence") or {}'),
            render_source.index('"alpha_strategy_count": independence.get("alpha_strategy_count")'),
        )

    def test_dashboard_surfaces_live_signal_conviction(self):
        source = Path("dashboard/app.py").read_text()

        self.assertIn("def _live_signal_conviction_dashboard", source)
        self.assertIn("load_validation_dashboard_summary", source)
        self.assertIn("def _compact_live_signal_conviction_summary", source)
        self.assertIn("def _regime_summary_display_rows", source)
        self.assertIn("def _render_live_signal_conviction", source)
        self.assertIn('"live_signal_conviction": live_signal_conviction', source)
        self.assertIn("Live Signal Conviction", source)
        self.assertIn("Regime-Level Conviction Summary", source)
        self.assertIn("Regime-Level Conviction Profiles", source)
        self.assertIn("Frozen Signals / Outcomes", source)
        self.assertIn("Pending Outcomes By Horizon", source)
        self.assertIn("Historical Prior Profiles", source)
        self.assertIn("Live Paper Profiles", source)
        self.assertIn("Combined Profiles", source)
        self.assertIn("Conviction Status Counts", source)
        self.assertIn('"conviction_number_policy": "no_naked_conviction"', source)
        self.assertIn('"required_context": "conviction_display + source_bucket + n + status"', source)
        self.assertIn('"conviction_display": row.get("conviction_display")', source)
        self.assertIn('"source_bucket": row.get("source_bucket")', source)
        self.assertIn('"n": row.get("n")', source)
        self.assertIn('"data_lag_filtered": row.get("data_lag_filtered")', source)
        self.assertIn('"regime_level_profiles": _conviction_profile_display_rows', source)
        self.assertIn('"regime_summary_rows": _regime_summary_display_rows', source)
        self.assertIn('"operational_calibrated_profiles": row.get("calibrated_profiles")', source)

    def test_dashboard_surfaces_performance_attribution(self):
        source = Path("dashboard/app.py").read_text()

        self.assertIn("PerformanceAttribution", source)
        self.assertIn("def _performance_attribution_dashboard", source)
        self.assertIn("def _compact_performance_attribution_row", source)
        self.assertIn("def _performance_attribution_breakdown_rows", source)
        self.assertIn("def _render_performance_attribution", source)
        self.assertIn('"performance_attribution": performance_attribution', source)
        self.assertIn("Performance Attribution", source)
        self.assertIn("Latest Attribution", source)
        self.assertIn("Return Breakdown", source)
        self.assertIn("Recent Attribution Runs", source)
        self.assertIn("Residual Contract", source)
        self.assertIn('"label": "residual_alpha_candidate"', source)
        self.assertIn('"not_proven_alpha": True', source)
        self.assertIn('"execution_authority": "none"', source)
        self.assertIn('"spy_beta_contribution": _json_safe_number(row.spy_beta_contribution)', source)
        self.assertIn('"qqq_beta_contribution": _json_safe_number(row.qqq_beta_contribution)', source)
        self.assertIn('"momentum_factor_contribution": _json_safe_number(row.momentum_factor_contribution)', source)
        self.assertIn('"residual_alpha_candidate": _json_safe_number(row.residual_alpha_candidate)', source)

    def test_dashboard_surfaces_alpha_validation_trend(self):
        source = Path("dashboard/app.py").read_text()
        pipeline_source = Path("services/pipeline.py").read_text()

        self.assertIn("AlphaValidationRun", source)
        self.assertIn("def _alpha_validation_trend_dashboard", source)
        self.assertIn("def _compact_alpha_validation_row", source)
        self.assertIn("def _render_alpha_validation_trend", source)
        self.assertIn('"alpha_validation_trend": alpha_validation_trend', source)
        self.assertIn("Alpha Validation Trend", source)
        self.assertIn("Recent Alpha Validation Runs", source)
        self.assertIn('"source_table": "alpha_validation_runs"', source)
        self.assertIn("persist_alpha_validation_run", pipeline_source)
        self.assertIn('"6e_alpha_validation_persistence"', pipeline_source)
        self.assertIn('"alpha_validation_run"', pipeline_source)

    def test_dashboard_surfaces_strategy_regime_gap_analysis(self):
        source = Path("dashboard/app.py").read_text()

        self.assertIn("def _strategy_regime_gap_analysis_dashboard", source)
        self.assertIn("load_strategy_regime_gap_analysis", source)
        self.assertIn("def _render_strategy_regime_gap_analysis", source)
        self.assertIn('"strategy_regime_gap_analysis": strategy_regime_gap_analysis', source)
        self.assertIn("Strategy Family / Regime Gap Analysis", source)
        self.assertIn("Coverage Overview", source)
        self.assertIn("Diagnostics Contract", source)
        self.assertIn("Regime Coverage Rows", source)
        self.assertIn("Family Coverage Rows", source)
        self.assertIn("Weak Family / Regime Rows", source)
        self.assertIn("Simultaneous Failure Regime Rows", source)
        self.assertIn("simultaneous_failure_regime_rows", source)
        self.assertIn("Research Queue", source)
        self.assertIn('"contract_version": "strategy_regime_gap_analysis_v1"', source)
        self.assertIn('"execution_authority": "none"', source)
        self.assertIn('"target_weight_mutation": "none"', source)

    def test_dashboard_surfaces_strategy_promotion_recommendations(self):
        source = Path("dashboard/app.py").read_text()

        self.assertIn("def _strategy_promotion_recommendations_dashboard", source)
        self.assertIn("load_strategy_promotion_recommendations", source)
        self.assertIn("def _render_strategy_promotion_recommendations", source)
        self.assertIn('"strategy_promotion_recommendations": strategy_promotion_recommendations', source)
        self.assertIn("Promotion / Degradation Recommendations", source)
        self.assertIn("Recommendation Overview", source)
        self.assertIn("Recommendation Contract", source)
        self.assertIn("Recommendation Counts", source)
        self.assertIn("Recommendation Rows", source)
        self.assertIn("Recommendation Policy", source)
        self.assertIn('"contract_version": "strategy_promotion_recommendations_v1"', source)
        self.assertIn('"recommendation_only": True', source)
        self.assertIn('"execution_authority": "none"', source)
        self.assertIn('"target_weight_mutation": "none"', source)

    def test_dashboard_summary_loads_alpha_decision_profiles(self):
        source = Path("dashboard/app.py").read_text()

        self.assertIn("def _alpha_decision_profiles_dashboard", source)
        self.assertIn("def _render_alpha_decision_profiles", source)
        self.assertIn("load_alpha_decision_profiles", source)
        self.assertIn('"alpha_decision_profiles": alpha_decision_profiles', source)
        self.assertIn('"contract_version": "alpha_decision_profiles_v1"', source)
        self.assertIn('"decision_input_only": True', source)
        self.assertIn('"recommendation_only": True', source)
        self.assertIn('"execution_authority": "none"', source)
        self.assertIn('"target_weight_mutation": "none"', source)
        self.assertIn("Alpha Decision Profiles", source)
        self.assertIn("Alpha Decision Overview", source)
        self.assertIn("Independence Consumption", source)
        self.assertIn('"raw_alpha_strategy_count": profiles.get("raw_alpha_strategy_count")', source)
        self.assertIn('"independence_adjusted_strategy_count": profiles.get("independence_adjusted_strategy_count")', source)
        self.assertIn('"effective_independent_alpha_count": independence.get("effective_independent_alpha_count")', source)
        self.assertIn('"raw_alpha_strategy_count": (recommendations.get("alpha_decision_profiles") or {}).get("raw_alpha_strategy_count")', source)
        self.assertIn("redundancy_multiplier", source)
        self.assertIn("gross_expected_edge", source)
        self.assertIn("net_edge_status", source)

    def test_dashboard_surfaces_alpha_decision_policy(self):
        source = Path("dashboard/app.py").read_text()
        pipeline_source = Path("services/pipeline.py").read_text()
        seed_source = Path("db/seed.py").read_text()

        self.assertIn("def _alpha_decision_policy_dashboard_status", source)
        self.assertIn("def _render_alpha_decision_policy", source)
        self.assertIn('"alpha_decision_policy_config": (alpha_decision_policy.value if alpha_decision_policy else {}) or {}', source)
        self.assertIn('"alpha_decision_policy": alpha_decision_policy', source)
        self.assertIn("Alpha Decision Policy", source)
        self.assertIn("Alpha Decision Policy Mode", source)
        self.assertIn("Gated Blockers", source)
        self.assertIn("evaluate_alpha_decision_policy", source)
        self.assertIn("default_alpha_decision_policy_config", pipeline_source)
        self.assertIn('"alpha_decision_policy_config": alpha_decision_policy_config', pipeline_source)
        self.assertIn('"alpha_decision_policy_config"', seed_source)
        self.assertIn('"mode": "observe"', seed_source)

    def test_dashboard_surfaces_alpha_decision_review_surface(self):
        source = Path("dashboard/app.py").read_text()

        self.assertIn("def _alpha_decision_review_surface_status", source)
        self.assertIn("def _render_alpha_decision_review_surface", source)
        self.assertIn("def _alpha_readiness_report_dashboard", source)
        self.assertIn("def _render_alpha_readiness_report", source)
        self.assertIn('"alpha_decision_review_surface": alpha_decision_review_surface', source)
        self.assertIn('"alpha_readiness_report": alpha_readiness_report', source)
        self.assertIn("Alpha Decision Review Surface", source)
        self.assertIn("Alpha Attribution Readiness", source)
        self.assertIn("Readiness Contract", source)
        self.assertIn("Strategy Readiness Rows", source)
        self.assertIn("attribution_trade_authority", source)
        self.assertIn("gated_authority_out_of_scope", source)
        self.assertIn("Review Checklist", source)
        self.assertIn("Statistical Maturity And Independence", source)
        self.assertIn("Net Alpha Review Rows", source)
        self.assertIn("Promotion Review Rows", source)
        self.assertIn("Strategy Cluster Review Rows", source)
        self.assertIn("PC Alpha Decision Before / After Rows", source)
        self.assertIn("PC Before / After Allocation Diagnostics", source)
        self.assertIn("no_naked_conviction_numbers", source)
        self.assertIn("promotion_rows_include_residual_alpha_and_cost_status", source)
        self.assertIn("strategy_counts_show_effective_independent_count", source)
        self.assertIn("residual_alpha_status", source)
        self.assertIn("cost_adjusted_edge", source)
        self.assertIn("effective_independent_alpha_count", source)

    def test_dashboard_surfaces_transaction_cost_gate(self):
        source = Path("dashboard/app.py").read_text()
        pipeline_source = Path("services/pipeline.py").read_text()

        self.assertIn("def _compact_transaction_cost_gate", source)
        self.assertIn('"transaction_cost_gate": _compact_transaction_cost_gate', source)
        self.assertIn("Transaction Cost Gate", source)
        self.assertIn("Transaction Cost Rows", source)
        self.assertIn('"broker": gate.get("broker")', source)
        self.assertIn('"execution_effect": gate.get("execution_effect")', source)
        self.assertIn("edge_to_cost_ratio", source)
        self.assertIn("evaluate_transaction_cost_gate", pipeline_source)
        self.assertIn("default_transaction_cost_gate_config", pipeline_source)
        self.assertIn('"6cc_transaction_cost_gate"', pipeline_source)
        self.assertIn('"transaction_cost_gate_config": transaction_cost_gate_config', pipeline_source)

    def test_dashboard_surfaces_evidence_cap_calibration(self):
        source = Path("dashboard/app.py").read_text()

        self.assertIn("load_evidence_cap_calibration_report", source)
        self.assertIn("def _evidence_cap_calibration_dashboard", source)
        self.assertIn("def _render_evidence_cap_calibration", source)
        self.assertIn('"evidence_cap_calibration": evidence_cap_calibration', source)
        self.assertIn("Evidence Cap Calibration", source)
        self.assertIn("Recommended Config", source)
        self.assertIn("Recommended Vote Thresholds", source)
        self.assertIn('"recommendation_only": True', source)
        self.assertIn('"execution_authority": "none"', source)
        self.assertIn('"target_weight_mutation": "none"', source)

    def test_dashboard_surfaces_portfolio_risk_diagnostic(self):
        source = Path("dashboard/app.py").read_text()
        pipeline_source = Path("services/pipeline.py").read_text()

        self.assertIn("def _compact_portfolio_risk_diagnostic", source)
        self.assertIn("def _render_portfolio_risk_diagnostic", source)
        self.assertIn('"portfolio_risk_diagnostic": _compact_portfolio_risk_diagnostic', source)
        self.assertIn("Portfolio Risk Diagnostic", source)
        self.assertIn("Target Historical VaR / CVaR", source)
        self.assertIn("Current Historical VaR / CVaR", source)
        self.assertIn("Target Scenario Losses", source)
        self.assertIn("Current Scenario Losses", source)
        self.assertIn("load_portfolio_var_cvar_diagnostic", pipeline_source)
        self.assertIn('"6cd_portfolio_var_cvar"', pipeline_source)
        self.assertIn('"portfolio_risk_diagnostic"', pipeline_source)

    def test_qc_yfinance_audit_cron_writes_audit_and_cron_telemetry(self):
        source = Path("cron/qc_yfinance_feature_audit.py").read_text()

        self.assertIn('audit_cron_run("qc_yfinance_feature_audit")', source)
        self.assertIn("run_audit(", source)
        self.assertIn("write_db=True", source)
        self.assertIn("audit.add_rows(1)", source)
        self.assertIn("unit_risk_count", source)
        self.assertIn("QC_YFINANCE_AUDIT_LOOKBACK_DAYS", source)


if __name__ == "__main__":
    unittest.main()
